apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codefresh
patches:
- path: route-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
resources:
- ../../base
